### ISSUE TITLE
Style confirmation and notify dialogs

### ISSUE THREAD

**Issue by megadr01d** [nao-pon/elFinder-nightly#8]
I found elFinder has some inline styling values which I find hard to style externally.
I don't think they're part of the client configuration options so how can I style the `// css` lines in the stylesheet?

`elfinder.full.js`
line 6894:

~~~{.js}
$.fn.elfinderdialog.defaults = {
	cssClass  : '',
	title     : '',
	modal     : false,
	resizable : true,
	autoOpen  : true,
	closeOnEscape : true,
	destroyOnClose : false,
	buttons   : {},
	position  : null,
	width     : 320, // css
	height    : 'auto',
	minWidth  : 200,
	minHeight : 110
}
~~~

style to:

~~~{.css}
.ui-dialog-content {
    width: auto;
}
~~~

`elfinder.full.js`
line 1762:

~~~{.js}
notify : this.dialog('', {
			cssClass  : 'elfinder-dialog-notify',
			position  : {top : '12px', right : '12px'}, // css
			resizable : false,
			autoOpen  : false,
			title     : '&nbsp;',
			width     : 280
		}),
~~~

style to:

~~~{.css}
.elfinder-dialog-notify {
    bottom: 40px;
    right: 30px;
}
~~~

**Comment by nao-pon** [comment]
@megadr01d How about "!important"
ex.
```css
div.elfinder-dialog {
  width: auto !important;
}

div.elfinder-dialog-notify {
  top: auto !important;
  left: auto !important;
  bottom: 40px !important;
  right: 30px !important;
}
```
